### ISSUE TITLE
Ménages/Entreprises/Institutions - Créer page de remerciements dans le CMS

### ISSUE THREAD

**Issue by factorx-paucot** [Factor-X/citizens-reserve#11]
Voir avec @jcarton pour les détails de l'appel.
Voir avec @florianjeanmart pour le JS.

**Comment by jvastenaekels** [comment]
@jcarton @florianjeanmart 
Voici l'URL http://citizensreserve.factorx.eu/confirmation/
http://citizensreserve.factorx.eu/nl/confirmation/ en NL
