### ISSUE TITLE
Ménages/Entreprises/Institutions - Kit de sensibilisation PDF

### ISSUE THREAD

**Issue by factorx-paucot** [Factor-X/citizens-reserve#2]
- Enlever la question de la page "account"
- Ajouter un lien dans le mail de confirmation

**Comment by jvastenaekels** [comment]
Version FR : 
http://citizensreserve.factorx.eu/wp-content/uploads/2015/01/Sensibilisation.pdf
(EDIT: en fait ca c'est pour les ménages)

**Comment by jvastenaekels** [comment]
-> Pas nécessaire en fait c'est déjà pris en charge correctement dans le mail de confirmation

**Comment by jcarton** [comment]
Julien,
Où se trouve la version NL? Je ne vois rien sur 
http://citizensreserve.factorx.eu/nl/wp-content/uploads/2015/01/Sensibilisation.pdf ...
