### ISSUE TITLE
Entreprises/Intitutions - Workflow - Page remerciements

### ISSUE THREAD

**Issue by factorx-paucot** [Factor-X/citizens-reserve#5]
# Client
### FELICITATIONS

Vous êtes officiellement notre 4567è réserviste énergétique
**[ :warning: A PRECISER ]** Vos actions cumulées s'élèvent à 114 kW. Félicitations !
**[ :information_source: moyenne des 12 1/4 d'heures entre 17h et 20h ]** Vous avez ajouté en moyenne 109.8181818182 kW dans la réserve d'effacement citoyenne pour la periode à risque (17h-20h). Elle s'élève désormais à 445 MW.

Récapitulatif des actions que vous avez indiquées :

|  | :warning: A PRECISER _ne pas implémenter_ |  |  |  |  |
| --- | --- | --- | --- | --- | --- |
| PC | Interruption | 2 kW | 19:30 | 7:30 | Extinction ordinateurs batiments B-C-D |
| Chauffage | Modération | 4 kW | 17:00 | 14:00 |  |
| Climatisation | Interruption | 5 kW | 18:00 | 13:00 |  |
| Eclairage extérieur | Interruption | 2 kW | 17:30 | 11:30 |  |
| Enseignes lumineuses | Modération | 1 kW | 17:30 | 11:30 |  |
| Moteurs | Modération | 100 kW | 17:00 | 3:00 |  |
# Workflow

Lorsqu'on arrive sur cette page (comprendre: lorsque le formulaire est complet), envoyer un mail récapitulatif ... :warning: à préciser)

Lorsqu'on arrive sur cette page, dumper le détail du calcul dans la console du browser. Les infos se trouvent dans _EffectiveReductionDTO_

**Comment by factorx-paucot** [comment]
Résumé fait

**Comment by jvastenaekels** [comment]
OK -> Juste ajouter dans la 1ère ligne du tableau récapitulatif 3e - 4e et 5e colonne : Réduction de puissance effective - Heure de début - Durée. Merci!
