### ISSUE TITLE
Ménages - Kit de sensibilisation PDF - Ecrire les fichiers PDF

### ISSUE THREAD

**Issue by factorx-paucot** [Factor-X/citizens-reserve#8]

**Comment by jvastenaekels** [comment]
Version FR : 
http://citizensreserve.factorx.eu/wp-content/uploads/2015/01/Sensibilisation.pdf

**Comment by jvastenaekels** [comment]
@jcarton 
Version NL:
http://citizensreserve.factorx.eu/wp-content/uploads/2015/01/Sensibilisatie.pdf
